    char Area_Code[4];
    char Airport_Ident[5];
    char ICAO_Code[3];
    char GLS_Ref_Path_Ident[5];
    char GLS_Category;
    unsigned char Continuation_Record_No;
    char GLS_Channel[6];
    char Runway_Ident[6];
    char GLS_Approach_Bearing[5];
    ARINC_Position Station_Position;
    char GLS_Station_Ident[5];
    unsigned char Service_Volume_Radius;
    char TDMA_Slots[3];
    float GLS_Approach_Slope;
    char Magnetic_Variation[6];
    char Station_Elevation[6];
    char Datum_Code[4];
    char Station_Type[4];
    char Station_Elevation_WGS84[6];
    unsigned int File_Record_Number;
    unsigned short Cycle_date;
    char Notes[70];
